@startuml
hide footbox

actor User
participant "NetLogo HPC Controller" as NetLogoController
participant Slurm
participant "NetLogo HPC Worker" as NetLogoWorker

User --> NetLogoController: Start NetLogo-HPC
activate NetLogoController

NetLogoController -> NetLogoController: Check (Concurrent) Jobs
note left
 Checking for running jobs loops trough them checking
 if they are not completed, cancelled or failed. If the
 amount of jobs running is lower than the maximum a
 new job will be submitted to slurm.
end note

NetLogoController --> Slurm: Submit job

Slurm --> NetLogoWorker: Run scheduled job
activate NetLogoWorker

NetLogoWorker --> NetLogoController: Connect to controller
note left
 Every message sent from a worker contains
 the identity of the worker which is based
 on the slurm job id. This gets used for
 checking the status of the job on the
 controller, which checks for failures
 and processing time left.
end note

NetLogoWorker --> NetLogoController: Get runNumber

NetLogoController -> NetLogoController: Check Worker
activate NetLogoController

NetLogoController --> Slurm: Check Job time
deactivate NetLogoController
note left
 This checks time left and status of the
 job. If the job was cancelled or killed,
 the runNumber will be returned to the
 queue if the run was not completed. 
end note

NetLogoController --> NetLogoWorker: Reply runNumber
note left
 This will contain a run number, if there is
 enough time left. Otherwise return a quit
 message instead. 
end note

NetLogoWorker -> NetLogoWorker: Start
activate NetLogoWorker

loop step < steps
 NetLogoWorker -> NetLogoWorker: Step
 NetLogoWorker --> NetLogoController: Report Data
 
 note left
  This reports the data generated by running a
  step of the simulation. The data will also be
  saved to a file by the worker as backup. The
  controller will assenble all the data in
  one big csv.
 end note
end loop

NetLogoWorker --> NetLogoController: Report Complete
deactivate NetLogoWorker
note left
 This is in reality a new "Get runNumber" to clear
 the previous one in the Controller so it is marked
 as completed and not resubmitted to the queue.
end note
@enduml
